
### login de un usuario 'organizer' editado desde la base de datos
### Este organizador no tiene ningun evento a su nombre
### (Si las credenciales son correctas, debe devolver 200)
POST http://localhost:9909/api/sessions/login
Content-Type: application/json  

{
  "email": "homerosanchez@gmail.com",
  "password": "12345678"
}

### Verifico que este iniciada la sesión
### 200 si esta todo bien (token vigente, datos auténticos, etc)
### 401 si se cerro la sesión o expiro el token 
GET http://localhost:9909/api/sessions/current

### Como este es un 'organizer', intento hacer un POST en 'events'
### 401 si expiro la sesión
### 400 si se trata de un evento repetido o tiene una fecha no futura
### 201 si todo sale bien
POST http://localhost:9909/api/events
Content-Type: application/json

{
    "title": "El fantasma de la opera",
    "description": "se trata de un fantasma",
    "date": "2026-10-01"
}

### Intentamos editar un evento que le pertenece al organizador que inicio sesión
### 200 si funciona (COMO AHORA SE TRATA DEL DUEÑO, DEBERIA DEVOLVER ESTO)
### 400 si no esta bien hecha la request
### 401 si no estoy autenticado
### 403 si se trata de un evento que no le pertenece
### 404 si no existe el evento
PUT http://localhost:9909/api/events/6ab9395088d96f02e96e7e0c
Content-Type: application/json

{
    "title": "El cisne blanco"
}


### PRIMERO: Iniciamos sesion con el organizador dueño del evento
POST http://localhost:9909/api/sessions/login
Content-Type: application/json  

{
  "email": "cosmefulanito@gmail.com",
  "password": "1122334455"
}

### Ahora estoy logueado con el organizador dueño del evento
### 200 si sale todo bien
### 401 si no inicie sesión
### 403 si no estoy autorizado
### 404 si el evento no existe (cambio ultimo digito de 5 a 6)
DELETE http://localhost:9909/api/events/6ab9d8be2e345f37012c62c5

### RUTA EXCLUSIVA PARA ADMINS
### Deberia devolver 403 
GET http://localhost:9909/api/sessions/listUsers